name: resource-hub
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: amitbhalla/playbooks
  build_command: npm run build
  run_command: npm run server
  http_port: 3001
  instance_size_slug: basic-xxs  # Smallest instance size, can be increased if needed
  instance_count: 1  # Number of instances
  health_check:
    http_path: /   # Path to health check
    initial_delay_seconds: 10
  routes:
  - path: /
  env:
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "3001"  # Make sure this matches the port in server.js
  - key: REACT_APP_BUILD_TIME
    scope: BUILD_TIME
    value: ${_self.app_name}-${_self.environment_name}-${_self.service_name}-${_self.git_commit_sha}
  cors:
    allow_origins:
      - regex: ".*"
  alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
